#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        TestClass.py
#
#  Project :     
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      katja2464$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################


__all__ = ["TestClass", "TestClassClass", "main"]

__docformat__ = 'restructuredtext'

import serial #added
import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(TestClass.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	TestClass.additionnal_import

# Device States Description
# No states for this device
ser = serial.Serial('COM6') #added

class TestClass (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(TestClass.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TestClass.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        TestClass.init_device(self)
        #----- PROTECTED REGION ID(TestClass.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TestClass.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(TestClass.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TestClass.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_weight_read = 0.0
        #----- PROTECTED REGION ID(TestClass.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TestClass.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(TestClass.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TestClass.always_executed_hook

    # -------------------------------------------------------------------------
    #    TestClass read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_weight(self, attr):
        self.debug_stream("In read_weight()")
        #----- PROTECTED REGION ID(TestClass.weight_read) ENABLED START -----#
        
        #added
        data1 = ser.read(size=10)       
        attr.set_value(float(data1.decode('UTF-8')))
        #----- PROTECTED REGION END -----#	//	TestClass.weight_read
        
       
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(TestClass.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TestClass.read_attr_hardware


    # -------------------------------------------------------------------------
    #    TestClass command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(TestClass.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TestClass.programmer_methods

class TestClassClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(TestClass.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TestClass.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'weight':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(TestClassClass, TestClass, 'TestClass')
        #----- PROTECTED REGION ID(TestClass.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TestClass.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
